app/urls.py
from django.urls import path, reverse  # Remova a vírgula aqui
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='home'),
    path('cadastro_roupa/', views.cadastro_roupa, name='CadastroRoupa'),
    path('roupa/<int:idroupa>', views.roupa_dinamico, name='roupa'),
    path('meu_carrinho', views.meu_carrinho, name="meu_carrinho"),
    path('checkout', views.checkout, name="checkout"),
    path('checkout_end', views.checkout_end, name="checkout_end"),
    path('get_checkout_session', views.get_checkout_session, name="get_checkout_session"),
    path('profile', views.user_profile, name='user_profile'),
    path('logout', views.logout_view, name='logout'),
    path('create-checkout-session', views.create_checkout_session, name='create_checkout_session'),
    path('roupa/<int:idroupa>/alugar', views.aluguel, name='aluguel')
]

suit2go/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('', include ('app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# This is not an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from .utils import generate_file_name
from django.contrib import admin
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialApp
from taggit.managers import TaggableManager

class Clientes(models.Model):
    id_clientes = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True)
    telefone = models.CharField(max_length=200, blank=True, null=True)
    data_nascimento = models.DateField(blank=True, null=True)
    cpf = models.CharField(max_length=11, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'clientes'
    def __str__(self):
        return self.nome


class Cor(models.Model):
    id = models.AutoField(primary_key=True)
    titulo=models.CharField(max_length=100)
    cor_code=models.CharField(max_length=8)

    class Meta:
        managed = True
        db_table = 'cor'
    def __str__(self):
        return self.titulo

class Estilo(models.Model):
    id = models.AutoField(primary_key=True)
    titulo=models.CharField(max_length=100)

    class Meta:
        managed = True
        db_table = 'estilo'
    def __str__(self):
        return self.titulo

class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    titulo=models.CharField(max_length=100)

    class Meta:
        managed = True
        db_table = 'categoria'
    def __str__(self):
        return self.titulo

class Tamanho(models.Model):
    id = models.AutoField(primary_key=True)
    titulo=models.CharField(max_length=100)

    class Meta:
        managed = True
        db_table = 'tamanho'
    def __str__(self):
        return self.titulo

class Marcas(models.Model):
    id_marca = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=False, null=False)
    class Meta:
        managed = True
        db_table = 'marcas'
    def __str__(self):
        return self.nome

class Roupas(models.Model):
    id_roupas = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    estilo = models.ForeignKey(Estilo, on_delete=models.CASCADE)
    tags = TaggableManager()

    def __str__(self):
        return self.nome

    class Meta:
        managed = True
        db_table = 'roupas'

class FotosRoupas(models.Model):
    id = models.AutoField(primary_key=True)
    roupa = models.ForeignKey(Roupas, on_delete=models.CASCADE)
    fotoUrl = models.ImageField(upload_to=generate_file_name)
    ordem = models.IntegerField(default=0)

    class Meta:
        managed = True
        db_table = 'fotos_roupa'

class SocialAppAdmin(admin.ModelAdmin):
    list_display = ('provider', 'name', 'client_id', 'secret', 'sites')
    search_fields = ('provider',)

    
class ProdutoVariacao(models.Model):
    id = models.AutoField(primary_key=True)
    produto = models.ForeignKey(Roupas, on_delete=models.CASCADE)
    tamanho = models.ForeignKey(Tamanho, on_delete=models.CASCADE)
    cor = models.ForeignKey(Cor, on_delete=models.CASCADE)
    preco_aluguel = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    disponibilidade = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'produto_variacao'

class FotosRoupaVariacao(models.Model):
    id = models.AutoField(primary_key=True)
    variacao = models.ForeignKey(ProdutoVariacao, on_delete=models.CASCADE)
    fotoUrl = models.ImageField(upload_to=generate_file_name)
    ordem = models.IntegerField(default=0)

    class Meta:
        managed = True
        db_table = 'fotos_roupa_variacao'

class Locacoes(models.Model):
    cliente_id = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    data_inicio = models.DateField(blank=True, null=True)
    data_termino = models.DateField(blank=True, null=True)
    valor_total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    data_negociacao = models.DateTimeField(auto_now_add=True)
    endereco_rua = models.CharField(max_length=200, blank=True, null=True)
    endereco_numero = models.CharField(max_length=200, blank=True, null=True)
    endereco_complemento = models.CharField(max_length=200, blank=True, null=True)
    endereco_bairro = models.CharField(max_length=200, blank=True, null=True)
    endereco_cidade = models.CharField(max_length=200, blank=True, null=True)
    endereco_cep = models.CharField(max_length=200, blank=True, null=True)
    
    class Meta:
        managed = True
        db_table = 'locacoes'

class ItensLocacao(models.Model):
    locacao = models.ForeignKey(Locacoes, on_delete=models.CASCADE)
    produto_variation = models.ForeignKey(ProdutoVariacao, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=1)
    preco_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = True
        db_table = 'itens_locacao'

app/templates/alugar.html
{% extends 'base.html' %}

{% block title %}Suit2Go - Alugar{% endblock %}

{% block content %}
<form method="post" action="{% url 'aluguel' idroupa=roupa.id_roupas %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>
{% endblock %}

app/templates/base_backup.html
{% load static %}

<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}SUIT2GO{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script>
        function updateAddressBar() {
            // Get the current URL without query parameters
            var urlWithoutQuery = window.location.origin + window.location.pathname;
            // Update the browser's address bar without triggering a page reload
            history.pushState(null, null, urlWithoutQuery);
        }
        updateAddressBar();
    </script>
</head>

<body>
    <header>
        <div class="navbar navbar-dark bg-dark navbar-expand-lg">
            <div class="container-fluid">
                <a href="{% url 'home' %}" class="navbar-brand d-flex align-items-center">
                    <strong>SUIT2GO</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </header>

    <main>
        {% block content %}
        <p>This is the content of another template.</p>
        {% endblock %}
    </main>

    <footer class="text-body-secondary py-5">
        <div class="container">
            <p class="mb-1">&copy; SUIT2GO </p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>


app/templates/cadastro_roupa.html
{% extends 'base.html' %}

{% block title %}Suit2Go - Cadastrar roupa{% endblock %}

{% block content %}
<div class="py-5 bg-body-tertiary">
    <div class="container">
        <h1>Tela de cadastro</h1>
        <form method="post" action="{% url 'cadastro_roupa' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {% if form.errors %}
                <p>Erros no formulário. Corrija-os e tente novamente.</p>
            {% endif %}

            {{ form.as_p }}

            <button class="btn btn-primary" type="submit">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/checkout.html
{% extends 'base.html' %}

{% block title %}Suit2Go - Carrinho{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
<div class='stepper-1'>
  <form action="{% url 'checkout' %}" method="post">
    {% csrf_token %}
    <div id="passo1">
      <h2>Informe o endereço de entrega</h2>
      {{ forms.endereco.as_p }}
      <div>
        <button  class='botao-step' type="button" onclick="controlState('passo2')">Próximo</button>
      </div>
    </div>
    <div id="passo2">
      <h2>Data da locação</h2>
      {{ forms.data.as_p }}
      <div>
        <button class='botao-step' type="button" onclick="controlState('passo1')">Anterior</button>
        <button class='botao-step' type="submit">Pagamento</button>
      </div>
    </div>
  </form>
</div>

<script>
  // pode adicionar passos extras ou remover se necessário
  var states = ["passo1", "passo2"];

  // Esta função controla a visibilidade das etapas
  function controlState(currentState) {
    const el = document.getElementById(currentState);
    el.style.display = "block";
    for (let state of states) {
      document.getElementById(state).style.display = 'none';
    }
    document.getElementById(currentState).style.display = 'block';
  }
  controlState(states[0]);
</script>
{% endblock %}

app/templates/checkout_end.html
{% extends 'base.html' %}

{% block title %}Suit2Go - Carrinho{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
<section id="success" class="hidden">
  <p>
    Obrigado pela confiança! Um e-mail de confirmação será enviado para <span id="customer-email"></span>.

    Caso tenha qualquer dúvida, envie uma mensagem para <a href="mailto:orders@example.com">orders@example.com</a>.
  </p>
</section>

<script>
  initialize();

  async function initialize() {
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    const sessionId = urlParams.get('session_id');
    const response = await fetch(`/get_checkout_session?session_id=${sessionId}`);
    const session = await response.json();

    if (session.status == 'open') {
      window.replace('http://localhost:8000/checkout.html')
    } else if (session.status == 'complete') {
      document.getElementById('success').classList.remove('hidden');
      document.getElementById('customer-email').textContent = session.customer_email
    }

    clearCart();
  }
</script>
{% endblock %}

app/templates/checkout_payment.html
{% extends 'base.html' %}

{% block title %}Suit2Go - Carrinho{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
<form>
  {% csrf_token %}
  <div id="checkout">
    <!-- Checkout will insert the payment form here -->
  </div>
</form>

<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'js/checkout.js' %}"></script>

<script>
  initializeCheckout();
</script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Header -->
{% load static %}
<header class="header_index">
    
    <div class="container px-4 px-lg-5 my-2">
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <form class="d-flex mt-3" role="search" action="{% url 'home' %}" method="get">
                    <div class="input-group mb-3">
                        <input class="form-control" type="search" name="q" placeholder="Pesquisar"
                            aria-label="Pesquisar" value="{{ q }}">
                        <button class="btn btn-index" type="submit"><i class="bi bi-search"></i></button>
                    </div>
                </form>
            </div>
        </div>
        <div id='icones-index' class="row">
            <div class="col-4">
                <div class="icon-container">
                    <a href="{% url 'home' %}?t=8" class="category-icon">
                        <button class="icon">
                            <img src="{% static 'img/man.png' %}" width='10' alt='Roupas Masculinas'>
                            <p class='icon-describer'>Masculinas</p>
                        </button>
                    </a>
                </div>
            </div>
            <div class="col-4">
                <div class="icon-container">
                    <a href="{% url 'home' %}?t=2" class="category-icon">
                        <button class="icon">
                            <img src="{% static 'img/woman.png' %}" width='11.5' alt='Roupas Femininas'>
                            <p class='icon-describer'>Femininas</p>
                        </button>
                    </a>
                </div>
            </div>
            <div class="col-4">
                <div class="icon-container">
                    <a href="{% url 'home' %}?t=10" class="category-icon">
                        <button class="icon">
                            <img src="{% static 'img/terno.png' %}" width='20' alt='Ternos Completos'>
                            <p class='icon-describer'>Ternos Completos</p>
                        </button>
                    </a>
                </div>
            </div>
            <div class="col-4">
                <div class="icon-container">
                    <a href="{% url 'home' %}?t=9" class="category-icon">
                        <button class="icon">
                            <img src="{% static 'img/shoe.png' %}" width='30' alt='Calçados'>
                            <p id='calçado' class='icon-describer'>Calçados</p>
                        </button>
                    </a>
                </div>
            </div>
            <div class="col-4">
                <div class="icon-container">
                    <a href="#" class="category-icon">
                        <button class="icon">
                            <img src="{% static 'img/heart.png' %}" width='25' alt='Favoritos'>
                            <p class='icon-describer'>Acessórios</p>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% if false %}
        <div class='d-flex align-items-center justify-content-center vh-100'>
            <div class='carrossel-bg'>
                <div id="carouselExample" class="carousel slide">
                    
                        <div id='foto-carrossel' class="carousel-inner">
                            {% for index, roupa in roupas_enumeradas %}
                                <div class="carousel-item {% if index == 0 %}active{% endif %}">
                                    <img src="/media/{{ roupa.fotosroupas_set.all.0.fotoUrl }}" width="500" height="500" class="d-block w-100 img-fluid" alt="...">
                                </div>
                            {% endfor %}
                        </div>
                    
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</header>
<!-- Section-->
<section>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% if roupas %}
    {% for roupa in roupas %}
        {% with variacao=roupa.produtovariacao_set.first %}
            {% if variacao %}
                {% include 'componentes/roupa_card.html' with roupa=roupa variacao=variacao %}
            {% endif %}
        {% endwith %}
    {% endfor %}
{% else %}
    <div class="row">
        <div class="col-12 text-center">
            <h1>Nenhuma roupa encontrada...</h1>
        </div>
    </div>
{% endif %}
        </div>
    </div>
</section>
{% endblock %}

app/templates/meu_carrinho.html
{% extends 'base.html' %}

{% block title %}Suit2Go - Carrinho{% endblock %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
<script>
  const debouncedRefresh = debounce(() => location.relod(), 300);

  function handleUpdateQuantity(productId, amount, price) {
    const cart = getCart();
    const updatedQuantity = updateCartProductQuantity(productId, amount);
    document.getElementById('itemQtd-' + productId).innerHTML = updatedQuantity;
    if (updatedQuantity <= 0) {
      alert('Produto removido do carrinho');
      document.getElementById('cartItem-' + productId).remove();
    }

    // Update cart value
    const priceDelta = parseFloat(price) * amount;
    const totalEl = document.getElementById("total-carrinho");
    const currentTotal = parseFloat(totalEl.innerHTML);
    totalEl.innerHTML = (currentTotal + priceDelta).toFixed(2);
  }

  function handleRemoveFromCart(productId) {
    removeFromCart(productId);
    alert('Produto removido do carrinho');
    document.getElementById('cartItem-' + productId).remove();
  }

  function handleCheckout() {
  }

  function handleContinueShopping() {
    alert('Continuar compras clicked');
  }
</script>
<div class='carrinhocontainer'>
  <div class='carrinho-header'>
    <img class='carrinho-icon' src="{% static  'img/shop-cart.png' %}">
    <h2>Carrinho de compras</h2>
  </div>

  <table class='cart' id="tableCartItems">
    <thead class='cart-prod-quant'>
      <tr>
        <th></th>
        <th>Produto</th>
        <th>Valor Total</th>
        <th>Quantidade</th>
        <th></th>
      </tr>
    </thead>
    <tbody id='itenscarrinho'>
      {% for item in carrinho %}
      <tr id="cartItem-{{item.produto.id}}">
        <td>
          <img src="media/{{ item.produto.fotosroupavariacao_set.all.0.fotoUrl }}" alt="{{ item.produto.name }}"
            class="cart-item-image">
        </td>
        <td id='itemcarrinho'>{{item.produto.produto.nome}}</td>
        <td id='itemcarrinho'>R$ {{item.produto.preco_aluguel}}</td>
        <td>
          <span id="itemQtd-{{item.produto.id}}">{{item.quantity}}</span>
          <button onclick="handleUpdateQuantity('{{item.produto.id}}', -1, '{{item.produto.preco_aluguel}}')">-</button>
          <button onclick="handleUpdateQuantity('{{item.produto.id}}', 1, '{{item.produto.preco_aluguel}}')">+</button>
        </td>
        <td>
          <button onclick="handleRemoveFromCart('{{item.produto.id}}')">X</button>
        </td>
      </tr>
      {% endfor %}

      {% if carrinho|length == 0 %}
      <tr>
        <td id='cart-none' colspan="5">Nenhum item no carrinho</td>
      </tr>
      {% endif %}
    </tbody>
    <tfoot>

    </tfoot>
  </table>
</div>
<div class='frete-container'>
  <div>
    <h>Resumo</h1>
  </div>
  <!-- <div>
    <label>
      <input type="radio" name="escolha" value="opcao1"> Retirada em guichê - Grátis
    </label>
    <br>
    <label>
      <input class='opt2' type="radio" name="escolha" value="opcao2"> Retirada em local desejado - Calcular
    </label>
  </div> -->
  <div id='linha-step' class='linha'>
  </div>
  <div>
    Preço total: R$ <span id="total-carrinho">{{ valorTotal }}</span>
  </div>
  <div id='linha-step' class='linha'>
  </div>
  <div>
    <a id='checkoutbutton' href="{% url 'checkout' %}">Checkout</a>
  </div>
</div>
{% endblock %}

app/templates/roupa.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Suit2Go - Roupa{% endblock %}

{% block content %}
<!-- Product section-->
<header>
    <div class="row-roupa">
        <div id='col-4-roupa' class="col-4">
            <div class="roupa-icon-container">
                <a href="#" class="category-icon">
                    <button class="icon">
                        <img src="{% static 'img/man.png' %}" width='10' alt='Roupas Masculinas'>
                        <p id='icon-descriver-roupa' class='icon-describer'>Masculinas</p>
                    </button>
                </a>
            </div>
        </div>
        <div class="col-4">
            <div class="roupa-icon-container">
                <a href="#" class="category-icon">
                    <button class="icon">
                        <img src="{% static 'img/woman.png' %}" width='12.5' alt='Roupas Femininas'>
                        <p id='icon-descriver-roupa' class='icon-describer'>Femininas</p>
                    </button>
                </a>
            </div>
        </div>
        <div class="col-4">
            <div class="roupa-icon-container">
                <a href="#" class="category-icon">
                    <button class="icon">
                        <img src="{% static 'img/terno.png' %}" width='20' alt='Ternos Completos'>
                        <p id='icon-descriver-roupa' class='icon-describer'>Ternos Completos</p>
                    </button>
                </a>
            </div>
        </div>
        <div class="col-4">
            <div class="roupa-icon-container">
                <a href="#" class="category-icon">
                    <button class="icon">
                        <img src="{% static 'img/shoe.png' %}" width='30' alt='Calçados'>
                        <p id='icon-descriver-roupa' class='icon-describer'>Calçados</p>
                    </button>
                </a>
            </div>
        </div>
        <div class="col-4">
            <div class="roupa-icon-container">
                <a href="#" class="category-icon">
                    <button class="icon">
                        <img src="{% static 'img/heart.png' %}" width='25' alt='Favoritos'>
                        <p id='icon-descriver-roupa' class='icon-describer'>Acessórios</p>
                    </button>
                </a>
            </div>
        </div>
    </div>
    </div>
</header>
<section class="py-5">
    <div id='roupa1'>
        <div class="roupa-container">
            <!--<h1  id="nome-roupa" class="display-5 fw-bolder">{{roupa.nome}}</h1>-->
            {% for variacao in variacoes %}
            {% if forloop.first %}
            <div class="fs-5 mb-5 variacoes-roupa-group" id="variacao-{{variacao.cor.id}}-{{variacao.tamanho.id}}">
                <!-- <span class="text-decoration-line-through">$ {{roupa.preco_aluguel}}</span> -->
                <!--<img id='card-logo' src="{% static 'img/creditcard.png' %}">-->
                <!-- ESSE CAMPO está na variação agora: <span id='preco-aluguel'>R$ {{roupa.preco_aluguel}}</span> gluacio -->
                {% comment %} <div class='fotos-roupas'>
                    <div class='fotos-all'>
                        {% for variacaoFoto in variacao.fotosroupavariacao_set.all%}
                        <div class='foto-roupa'>
                            <img class='roupa-variacao' src="/media/{{variacaoFoto.fotoUrl}}"></img>
                        </div>
                        {% endfor%}
                    </div> {% endcomment %}
                    <img class='imagem-main img-fluid' src='/media/{{roupa.fotosroupas_set.all.0.fotoUrl}}'>
                </div>
                <div class='roupa-final'>
                    <div class='details-section'>
                        <h1 id="nome-roupa" class="display-5 fw-bolder">{{roupa.nome}}</h1>
                        <div id='preco-cartão'>
                            <img id='card-logo' src="{% static 'img/creditcard.png' %}">
                            <h1 id='RS'> R$ <span id='preco-alugar'
                                    data-default-price="{{variacao.preco_aluguel}}">{{variacao.preco_aluguel}}</span>
                            </h1>
                        </div>
                        <div class='colors'>
                            <p>Cores:</p>
                            {% for cor in cores %}
                            <button type="button" data-color-id="{{cor.id}}" class="btn-color"
                                style="background-color: {{cor.cor_code}};"
                                onclick="selecionarCor({{cor.id}})"></button>
                            {% endfor %}
                        </div>
                        <p>Tamanhos:</p>
                        <div class='tamanhos-container'>
                            {% for variacao in variacoes %}
                            <button type="button" data-color-id="{{variacao.cor.id}}"
                                data-price="{{variacao.preco_aluguel}}" data-tamanho-id="{{ variacao.tamanho.id }}"
                                data-variacao-id="{{variacao.id}}" class="btn btn-size" style="display:none"
                                onclick="selecionarTamanho(this)">
                                {{ variacao.tamanho.titulo }}
                            </button>
                            {% endfor %}
                            <p class="color-desc">Selectione uma cor</p>
                        </div>
                        <div class='botão-aluguel'>
                            <button id='add-to-cart' class="btn btn-outline-dark flex-shrink-0" type="button"
                                disabled="true" onclick="handleAddToCart('{{roupa.nome}}')">
                                Alugar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor%}
        </div>
    </div>
    <div class="linha"></div>
    <div class='desc-container'>
        <img class='desc-logo' src='{% static "img/calendar.png" %}' />
        <p class='desc'> Cancelamento gratuito em até 48 horas </p>
    </div>
    <div class='desc-container'>
        <img class='desc-logo' src='{% static "img/location.png" %}' />
        <p class='desc'> Retirada no balcão ou em local desejado </p>
    </div>
    <div class='desc-container'>
        <img class='desc-logo' src='{% static "img/ruler.png" %}' />
        <p class='desc'> Atenção as medições do item </p>
    </div>
</section>
<div class="linha"></div>
<script>
    var corSelecionado = null;
    var variacaoId = null;

    function selecionarTamanho(tamanho) {
        variacaoId = tamanho.dataset.variacaoId;
        var preco = tamanho.dataset.price;
        var tamanhos = document.getElementsByClassName("btn-size")
        document.getElementById("preco-alugar").innerText = preco

        for (const t of tamanhos) {
            if (tamanho.dataset.variacaoId == t.dataset.variacaoId) {
                t.classList.add("select")
            } else {
                t.classList.remove("select")
            }
        }
        document.querySelector(".color-desc").style.display = "false";
        document.getElementById("add-to-cart").removeAttribute("disabled");
    }

    function selecionarCor(id) {
        corSelecionado = id;
        tamanhoSelecionado = null;
        document.getElementById("preco-alugar").innerText = document.getElementById("preco-alugar").dataset.defaultPrice
        var cores = document.getElementsByClassName("btn-color")
        for (const cor of cores) {
            if (cor.dataset.colorId == corSelecionado) {
                cor.classList.add("select")
            } else {
                cor.classList.remove("select")
            }
        }

        var tamanhos = document.getElementsByClassName("btn-size")
        for (const tamanho of tamanhos) {
            var corId = tamanho.dataset.colorId
            if (corId == id) {
                tamanho.style.display = "block"
            } else {
                tamanho.style.display = "none"
            }
        }
        document.getElementById("add-to-cart").setAttribute("disabled", true);
        document.querySelector(".color-desc").style.display = "none";

        //atualizarImagemPrincipal(imagemUrl);
    }

    function atualizarImagemPrincipal(imagemUrl) {
        const imagemPrincipal = document.querySelector('.imagem-main');
        imagemPrincipal.setAttribute('src', imagemUrl);
    }

    document.addEventListener('DOMContentLoaded', function () {
        // Obtém todas as imagens de variação
        const imagensVariacao = document.querySelectorAll('.roupa-variacao');

        // Adiciona um evento de clique a cada imagem de variação
        imagensVariacao.forEach(function (imagem) {
            imagem.addEventListener('click', function () {
                // Obtém o src da imagem de variação clicada
                const src = imagem.getAttribute('src');

                // Chama a função para atualizar a imagem principal
                atualizarImagemPrincipal(src);
            });
        });
    });
    function handleAddToCart(name) {
        addToCart(variacaoId, name, 1);
        alert(`Produto adicionado ${variacaoId}`);
    }
</script>
{% endblock %}